EXPERIMENT_NAME: 'test-simple-md4allDDa-robotcar'

LOAD:
  CHECKPOINT_PATH: '/mnt/code/md4all/checkpoints/md4allDDa_robotcar.ckpt'

DATASET:
  AUGMENTATION:
    CROP:
      HEIGHT: 768
      WIDTH: 1280
    RESIZE:
      WIDTH: 544
    NORMALIZE:
      MODE: 'Image' # Use Image mode if daytime is not known a priori

LOSS:
  PHOTOMETRIC:
    WEIGHT: 0.0
  SMOOTHNESS_WEIGHT: 0.0
  VELOCITY_WEIGHT: 0.0
  SUPERVISED:
    WEIGHT: 1.0
