EXPERIMENT_NAME: 'train-md4allDDa-nuscenes'

SAVE:
  CHECKPOINT_PATH: 'log/checkpoints/md4allDDa_nuscenes'

LOAD:
  DAY_NIGHT_TRANSLATION_PATH: '/mnt/data/nuscenes/trainval/translated/night'
  DAY_CLEAR_DAY_RAIN_TRANSLATION_PATH: '/mnt/data/nuscenes/trainval/translated/rain'
  DAYTIME_TRANSLATION_TEACHER_PATH: '/mnt/code/md4all/checkpoints/baseline_teacher_nuscenes.ckpt'

DATASET:
  AUGMENTATION:
    GAUSSIAN_NOISE:
      PROBABILITY: 0.5
    NORMALIZE:
      MODE: 'Daytime'
    DAY_NIGHT_TRANSLATION:
      PROBABILITY: 0.33
    DAY_CLEAR_DAY_RAIN_TRANSLATION:
      PROBABILITY: 0.5

LOSS:
  PHOTOMETRIC:
    WEIGHT: 0.0
  SMOOTHNESS_WEIGHT: 0.0
  VELOCITY_WEIGHT: 0.0
  SUPERVISED:
    WEIGHT: 1.0
